botpress/documentation

pages/cloud/studio/variables.mdx

Fixing the documentation part about how to use session variables

(fix):sessionVar_fix

---

pages/cloud/channels/whatsapp.mdx

Updated WhatsApp integration page to include new behaviors around choices and dropdowns

WhatsApp dropdown update

---

pages/cloud/toolbox/execute-code.mdx

Adds info on coming from other programming languages

feat: add info about converting code into javascript

---

pages/cloud/channels/webchat.mdx

Content on Webchat using React.js

feat(webchat): added react docs

---

pages/cloud/_meta.json
pages/cloud/channels/webchat.mdx
pages/cloud/embedding-webchat-options/react-app.mdx
pages/cloud/embedding-webchat-options/webflow.mdx

docs: added webflow and react docs

---

pages/cloud/studio/tables.mdx

Link ->  
https://documentation-git-phaddssearchtablescode.botpress.sh/docs/cloud/studio/tables/#basic-usage-and-pagination
:)

docs: adds search table via code

---

pages/cloud/toolbox/capture-information.mdx

Fixes Below Discord Issues
[Issue 1](https://www.notion.so/Validation-in-Capture-Info-1c0ded4081834bffb58f38a97383ffe5?pvs=4)
[Issue 2](https://www.notion.so/DateTime-formatting-ba7a29e4e7e64403867d7abc8a03f00e?pvs=4)
[Issue 3](https://www.notion.so/DateTime-formatting-94271a44366d4b5f9be816353e9e29b1?pvs=4)

feat(capture-info): adds datetime formatting examples

---

pages/cloud/studio/variables.mdx

updatin how to call an output variable of a workflow, and some spelling mistakes - suggested by Grammarly.
Referring to this conversation:
https://discord.com/channels/1108396290624213082/1155911468320043038/1157076753865506910

Update how to call an output variable

---

pages/cloud/studio/variables.mdx
pages/cloud/toolbox/_meta.json

- changes about the location of the variables tab
- added examples on usage of different types of variables in code card
Additional Fix
- Typo to the meta.json for Table Cards in the sidebar

fix(variables): added examples of usage and location of this option

---

pages/cloud/toolbox/capture-information.mdx

- added info about variable usage in retries option in capture card

feat(retries): added info about variables

---

pages/cloud/studio/agents.mdx

https://botpress.com/docs/cloud/studio/agents/#personality-agent has the wrong video :
https://www.youtube.com/watch?v=D9EGSzKy-N0

fix: update the youtube video

---

pages/cloud/studio/knowledge-base.mdx

adds the max url length for kbs

docs: add max url length

---

pages/cloud/channels/whatsapp.mdx

Related to: https://github.com/botpress/botpress/pull/12818

feat: add the WhatsApp location section

---

pages/cloud/studio/explorer.mdx
pages/cloud/studio/knowledge-base.mdx

- this PR adds information about scoping KB by folders

fix(kb-docs): added folder scoping info

---

pages/cloud/toolbox/execute-code.mdx

feat(code card): additional information on version

---

pages/cloud/studio/variables.mdx

https://documentation-git-gc-special-variables.botpress.sh/docs/cloud/studio/variables/#special-variables

feat: add special variables section

---

pages/cloud/exporting-bot-data/exporting-conversations/with-the-api.mdx

https://documentation-git-gc-improves-bot-export.botpress.sh/docs/cloud/exporting-bot-data/exporting-conversations/with-the-api/

chore: separate methods of getting convs

---

pages/cloud/channels/slack.mdx

Added Tips section to Slack channel, like we have in WhatsApp. It's to show where to get the users information.

feat(slack): Added #tips section

---

pages/cloud/channels/instagram.mdx

Adding notes and links to review and links to permission

feat(instagram): Adding notes and links to review and links to permission

---

pages/cloud/channels/telegram.mdx

Adding the tags used in the event of telegram under the Tips section

feature(telegram): adding tips

---

pages/cloud/agent-handoff/zendesk.mdx

Note is to use the web chat and not the emulator

fix(zendesk): added a note

---

pages/cloud/getting-started/_meta.json
pages/cloud/getting-started/platform-limits.mdx

https://documentation-git-gui-platform-limits.botpress.sh/docs/cloud/getting-started/platform-limits/

feat: add platform limits page

---

pages/cloud/channels/whatsapp.mdx

Reverts botpress/documentation#205

Revert "docs(wa): remove mention to business account"

---

pages/cloud/toolbox/capture-information.mdx

https://documentation-git-phaddrawinputkbsearch.botpress.sh/docs/cloud/toolbox/capture-information/#answer-from-a-knowledge-base

docs: using raw input kb search

---

pages/cloud/channels/instagram.mdx
pages/cloud/channels/messenger.mdx

Trying to give more context and informations to the users who want to install these integrations, they have been complaining a lot on how hard it is to install.

docs: improvements in messenger and instagram documentation

---

readme.md

changes getting started to recommend tilt

docs: change readme to use tilt

---

pages/cloud/channels/whatsapp.mdx

Added a step for addressing and solving the messaging issue.

Update - Whatsapp Permissions

---

pages/cloud/toolbox/events-triggers.mdx

Added Fixed Schedule - Trigger & Conversation ID

Update - Triggers

---

pages/cloud/studio/tables.mdx

Added Filtering options from the UI

Added Filtering Options

---

pages/developers/cli.mdx
pages/developers/getting-started.mdx
pages/developers/howTo/build-integration.mdx

Removed `bp dev` command usage from the docs

removed bp dev

---

pages/cloud/studio/agents.mdx

Kb Agent(Chunks + Model Strategy)

---

scripts/generateApiDocumentationPage.ts
scripts/generateApiDocumentationPage.types.ts

feat(api-docs): add params descriptions

---

pages/cloud/admin-dashboard/managing-workspaces.mdx

adds documentation for realtime collaboration

docs: realtime collab
